
export const GET_AUTH_STATUS = 'GET_AUTH_STATUS';
export const GET_ARTICLES = 'GET_ARTICLES';
export const GET_ARTICLES_ERROR = 'GET_ARTICLES_ERROR';
export const GET_FAVOURITE_ARTICLES = 'GET_FAVOURITE_ARTICLES';
export const GET_NOTIFY = '';
export const GET_SOURCES = 'GET_SOURCES';
export const GET_FAVOURITE_COUNT = 'GET_FAVOURITE_COUNT';
